### ISSUE TITLE
potential typo in configuration

### ISSUE THREAD

**Issue by laurentsenta** [multiformats/github-mgmt#70]
There might be a typo here; we use `github-mgmt-stewards` but the team is `github-mgmt stewards` (with a space):

https://github.com/multiformats/github-mgmt/blob/28a93efb193a21ce673a4dbff15146f20ef868f5/github/multiformats.yml#L398-L400

**Comment by galargh** [comment]
GitHub translates team with name `github-mgmt stewards` in org `multiformats` to `@multiformats/github-mgmt-stewards` ID.
